// <auto-generated />
using FNZ.Data.Data;
using FNZ.Share.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FNZ.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180704164239_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FNZ.Share.Models.Animal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedToSystemAt");

                    b.Property<DateTime>("AdoptionDate");

                    b.Property<double>("Age");

                    b.Property<string>("Breed");

                    b.Property<DateTime>("FoundAt");

                    b.Property<int>("MaxWeight");

                    b.Property<string>("Name");

                    b.Property<long?>("PostId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("FNZ.Share.Models.Moderator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<string>("PasswordHash");

                    b.HasKey("Id");

                    b.ToTable("Moderators");
                });

            modelBuilder.Entity("FNZ.Share.Models.MoneyCollection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndDate");

                    b.Property<long>("MoneyTarget");

                    b.HasKey("Id");

                    b.ToTable("MoneyCollections");
                });

            modelBuilder.Entity("FNZ.Share.Models.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedAt");

                    b.Property<string>("Author");

                    b.Property<int>("Category");

                    b.Property<string>("Content");

                    b.Property<string>("PhotoPath");

                    b.Property<DateTime>("RequestSentAt");

                    b.Property<string>("RequestSentBy");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("FNZ.Share.Models.Request", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AcceptanceDate");

                    b.Property<long?>("PostId");

                    b.Property<DateTime>("RefusalDate");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("FNZ.Share.Models.Tab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("PhotoPath");

                    b.Property<int>("TabCategory");

                    b.HasKey("Id");

                    b.ToTable("Tabs");
                });

            modelBuilder.Entity("FNZ.Share.Models.Animal", b =>
                {
                    b.HasOne("FNZ.Share.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId");
                });

            modelBuilder.Entity("FNZ.Share.Models.Request", b =>
                {
                    b.HasOne("FNZ.Share.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId");
                });
#pragma warning restore 612, 618
        }
    }
}
